services:
  frontend:
    image: ransika26/demo-frontend:latest  # Image from Docker Hub
    container_name: frontend-container
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - fs-app

  backend:
    image: ransika26/demo-backend:latest  # Image from Docker Hub
    container_name: backend-container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/ums
    depends_on:
      - mongo
    networks:
      - fs-app

  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27016:27017"
    volumes:
      - mongo-data:/data/ums  # Persistent storage for MongoDB data
    networks:
      - fs-app

volumes:
  mongo-data:

networks:
  fs-app:
    driver: bridge